# Generated by Django 5.2.15 on 2026-06-16 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineLibrary', '0007_alter_book_publisher_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='OnlineLibrary.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='OnlineLibrary.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ForeignKey(default=20, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='OnlineLibrary.photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ForeignKey(default=11, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OnlineLibrary.photo'),
        ),
    ]
